#====================================================================================================================
# AI Coding Agents / node24 https://hub.docker.com/_/node
#====================================================================================================================
services:
  ai-agents-gdc:
    build: .
    image: ai-agents-python:latest
    container_name: ai-agents-gdc
    user: ${USER_ID?err}:${GROUP_ID?err}
    working_dir: "/usr/workspace/ai-agents/gaming-data-collection"
    environment:
      - TZ=Asia/Tokyo
      - HOME=/usr/home
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "../../../../:/usr/workspace"
      - "../../../../user-home:/usr/home"
      - "../../../../../gaming-data-collection/gaming-data-collection:/usr/app/gaming-data-collection"
    networks:
      turing-net:
    command: /bin/bash
